### ISSUE TITLE
Improve usability on mobile

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/portfolio-template#11]
At the moment, we have a few screen sizes hardcoded to allow this to work on mobile. It would be good if we could make this more responsive.

**Comment by amalaabraham** [comment]
Myself (@amalaabraham), @Apra487 and @hbFree  will be working on this issue. Thank you :)

**Comment by Apra487** [comment]
Hey @wrussell1999 , we found a bug for slimer devices like galxy fold. It is not scaling properly.

<img width="444" alt="galxy fold issue" src="https://user-images.githubusercontent.com/54775196/106567106-4048b900-6557-11eb-9ed3-649f0eef9f2f.png">

**Comment by wrussell1999** [comment]
@amalaabraham just a heads up for something to look for ^

**Comment by Apra487** [comment]
> @amalaabraham just a heads up for something to look for ^

hey @wrussell1999  we are working as a team I made a pr recently.Please review it.
