### ISSUE TITLE
Add social media links

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/portfolio-template#12]
At the moment, people can see your awesome work but there's no way for them to get in touch with you and network!

## Suggestion

- Navbar dropdown
- Footer with icons

Open to your creativity here, or maybe having multiple options and anyone using this template can pick one or the other.

**Comment by saum7800** [comment]
Hey @wrussell1999. Me(Saumya Gandhi), Mayra and Sachin @sachsom will be working on this issue. Thanks :)

**Comment by sachsom95** [comment]
<img width="435" alt="Screenshot 2021-02-03 at 10 42 45" src="https://user-images.githubusercontent.com/55349036/106735776-8dd32d80-660c-11eb-946c-127907878051.png">

This is the MVP as of now

**Comment by saum7800** [comment]
PR is merged. This issue can be closed now. Thanks :)
