### ISSUE TITLE
Add CV/Resume

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/portfolio-template#13]
This portfolio acts very like your resume or CV, but doesn't contain it.

Add a button for people to view your resume and potentially access it by going to `/cv`

**Comment by anjali-001** [comment]
Hey @wrussell1999. Me( @anjali-001 ), Shivam(@devthepenguin) and Siddesh(@SiddeshSambasivam) will be working on this issue. Thanks :)
