### ISSUE TITLE
Template more of the code

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/portfolio-template#19]
At the moment, there's a bit of repeated code between Projects, Experience, and Education cards. To improve the usability of the code, it would be great to reduce as much repeated code, and clean up the structure to make it easier to maintain.

**Comment by anjalisoni3655** [comment]
@wrussell1999 me and my team  willing to take up this task. Can you assign this to us.

**Comment by Korusuke** [comment]
@anjalisoni3655 if y'all are working on #27, this issue is free right?

**Comment by anjalisoni3655** [comment]
> @anjalisoni3655 if y'all are working on #27, this issue is free right? 

Yes sure,

**Comment by felixfaisal** [comment]
I would like to work on this @wrussell1999 @Korusuke
