### ISSUE TITLE
Add links to the navbar

### ISSUE THREAD

**Issue by SiddeshSambasivam** [MLH-Fellowship/portfolio-template#26]
- add links to navbar to navigate to the relevant sections (eg. projects, experience) of the page

**Comment by SiddeshSambasivam** [comment]
We (@SiddeshSambasivam , @anjali-001, @devthepenguin) are currently working on this issue :smile:

**Comment by anjalisoni3655** [comment]
@SiddeshSambasivam This issue was already mentioned in the repo. Please have a look.

**Comment by SiddeshSambasivam** [comment]
Thank you for mentioning @anjalisoni3655!
