### ISSUE TITLE
Center the logo and navlink

### ISSUE THREAD

**Issue by GunaShekar02** [MLH-Fellowship/portfolio-template#43]
![image](https://user-images.githubusercontent.com/43517435/106621003-21b6e200-6598-11eb-848e-60c58172a4fb.png)
As it can be seen in the above picture, the link to resume is not vertically centered, and the same is with the logo. This is because there is a padding-top given to the navbar which has to be removed in order to center the nav-items.

**Comment by m2chan** [comment]
My team can take this, good catch

**Comment by GunaShekar02** [comment]
Hey, @m2chan! I had issued a PR just before your comment, I'm sorry, should've claimed it before doing that. 
However, do you mind looking at #45? It's related to the same file.
