### ISSUE TITLE
Add/Fix Social twitter/og meta tags

### ISSUE THREAD

**Issue by Korusuke** [MLH-Fellowship/portfolio-template#46]
- There are already some og tags [here](https://github.com/MLH-Fellowship/portfolio-template/blob/1980d6d597e004eed298b0a3259f937b0717ee4d/_includes/header.html#L5-L9) but from my initial testing, the image is not showing up in the preview.
- I also think that we can have the title and description customizable via the config file, maybe have some default values though
-  Add [twitter card tags
](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started)

https://metatags.io/ can be used for testing if everything works as intended

**Comment by jkmartindale** [comment]
@jackbisceglia, @gracewgao, and I will work on this!
