### ISSUE TITLE
Add Code_Of_Conduct

### ISSUE THREAD

**Issue by emmysteven** [MLH-Fellowship/portfolio-template#5]
Hello,

I want to discuss this first before making a pull request.
It would be nice for this project to have a **code of conduct** so that contributors will know what is expected of them.

I would love to add that the code of conduct myself, and for that to happen I'll be needing the **email address** where violation(s) of conduct will be reported to.

Warm Regards!

**Comment by wrussell1999** [comment]
Just added the MLH Code of Conduct to their repository. Happy Hacking!

https://github.com/MLH-Fellowship/portfolio-template/commit/6d67111e29f6c60984411ab28800e773aab32121
