### ISSUE TITLE
Make blog posts easier to find

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/portfolio-template#9]
At the moment, you can add blog posts to projects, and you can click through to them. This isn't very obvious at the moment, so could we improve this?

Maybe include a navigation bar?

**Comment by anjalisoni3655** [comment]
@wrussell1999 Do you mean a navigation bar at the top, with all the options, like Home,blogs, CV, etc. And on clicking on blogs option, the list of blogs will be displayed.

**Comment by wrussell1999** [comment]
Something like that yes! I'll leave it up to you folks to decide how you want to design it!

**Comment by YuanSamuel** [comment]
Heyo, my team and I will work on this issue; could you assign it to us?

**Comment by RashikaKarki** [comment]
Closing this issue. Feel free to reopen it if needed.
